project:
  type: website
  output-dir: docs
  
website:
  title: "Jordan Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
    tools:
      - icon: github
        href: https://github.com/JordanStats
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Alan Jordan"

format:
  html:
    theme: default
    toc: true

editor: source

